### ISSUE TITLE
Story #5/6 - Unordered (and too many) informations on my reservation page

### ISSUE THREAD

**Issue by GaetanoPrudente** [MattCamp44/Software-Engineering-2-team10#1]
As a student when i access to the page dedicated to my reservations, i want to see only my active (and future reservations).
so i don't care to see my past/cancelled reservations, and i expect to see my reservation ordered by date, so i can easily know what is my next lecture

**Comment by aureliocirella** [comment]
Fixed in commit 8e76e43901599c23c6e4f5ce7db8357f5b54d381
