### ISSUE TITLE
Calendar page for students - change text colors and time format

### ISSUE THREAD

**Issue by martinalilla** [MattCamp44/Software-Engineering-2-team10#10]
As a student, I ask you to change text colors inside the boxes in the calendar page, because they're too gaudy and the contrast between yellow/red/blue makes difficult the reading. 
Furthermore, I noticed that inside the box there are times in a format that is different from that used in the left column (eg. 14:00 vs 2 pm). I suggest you to choose and use one single format because the user may be confused and also for a matter of consistency.

**Comment by aureliocirella** [comment]
Solved in 3228a29
